import { mistral } from "@ai-sdk/mistral";
import { generateObject } from "ai";
import { vocabularySchema } from "./dialog.schema";

export const generateVocabulary = async ({
  language,
  dialogue,
}: {
  dialogue: string;
  language: string;
}) => {
  const result = await generateObject({
    model: mistral("mistral-large-latest"),
    system: `context:
        You are VOCABULARY Generator, an application that takes a dialogue and generates a best vocabulary.
        You are an expert of the ${language}, able to generate the best vocabulary for a given dialogue.
        
        Goal: 
        You need to generate a vocabulary for the given dialogue.
        
        Criteria: 
        - The vocabulary must be generated based on the given dialogue.
        - The vocabulary must be the best vocabulary for the given dialogue.
        - The vocabulary must be generated by an expert of the ${language}.
        - The vocabulary must be have a good definition and example.
        - The vocabulary must be in ${language} language.`,
    prompt: dialogue,
    schema: vocabularySchema,
  });

  const vocabulary = result.object;
  if (!vocabulary) {
    throw new Error("Failed to generate vocabulary");
  }

  return vocabulary;
};
